name: dtalk
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.2 <3.0.0'


dependencies:
  args: ^2.3.0
  dtalk_robot:
    git: https://github.com/LaelLuo/dtalk_robot.git

dev_dependencies:
  lints: ^5.1.1
