name: dtalk
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  # Allow Dart 3.x so we can use the new cross-compilation support in CI.
  sdk: '>=2.17.2 <4.0.0'


dependencies:
  args: ^2.3.0
  dtalk_robot:
    git: https://github.com/LaelLuo/dtalk_robot.git
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.2
